// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AwsButton: typeof import('./components/AwsButton.vue')['default'];
    ShowButton: typeof import('./components/ShowButton.vue')['default'];
    Spinner: typeof import('./components/Spinner.vue')['default'];
  }
}

export {};
